### ISSUE TITLE
ice-builder-xcode is support mac OS 10.13.6 ?

### ISSUE THREAD

**Issue by guoshimeihua** [zeroc-ice/ice-builder-xcode#2]
Now I have a problem not find <objc/Ice/Config.h>文件？
![2018-09-20 10 15 54](https://user-images.githubusercontent.com/7576393/45791939-50c9a300-bcbe-11e8-97e8-be07fae68456.png)
![2018-09-20 10 16 23](https://user-images.githubusercontent.com/7576393/45791940-51623980-bcbe-11e8-9f03-3d3ba03594f4.png)

**Comment by externl** [comment]
Hi @guoshimeihua 

Ice Builder for Xcode is not responsible for configuring `Additional SDKS`, only for compiling Slice files. If you're having issues using Ice please post on our forms at http://forums.zeroc.com.

(In this case I suspect your path is incorrect. The latest version of IceTouch is `v3.6.4`. Please refer to our [documentation](https://doc.zeroc.com/ice/3.6/ice-touch-release-notes/using-the-ice-touch-binary-distribution) for configuring Additional SDKs)

**Comment by externl** [comment]
@guoshimeihua We tested our demos and there does seems to be some issue with including the SDK in Xcode 10. We're investigating.

**Comment by guoshimeihua** [comment]
@externl Have you found a solution to the Xcode10 problem ？

**Comment by externl** [comment]
@guoshimeihua So far the only workaround is to not use the "Additional SDKs" setting and to manually set the header and library search paths. We've updated our demos on the 3.7 branch to do this.
